version: 2
builds:
  - main: .
    binary: simplemdm-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/dimer47/simplemdm-cli/cmd.Version={{.Version}}
      - -X github.com/dimer47/simplemdm-cli/cmd.Commit={{.Commit}}
      - -X github.com/dimer47/simplemdm-cli/cmd.Date={{.Date}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
